### ISSUE TITLE
Main menu styling

### ISSUE THREAD

**Issue by benorgan** [redacademy/cnh-fall-2018#1]
The top menu is looking good but a few issues (which you may already be aware of):

- There's a tiny gap between the menu and the dropdown which means if you're not quick moving from the menu to the dropdown then the dropdown disappears
- When you hover over the submenu items they move slightly 
- On mobile when the menu expands the text is squashed initially, try moving the menu into / out of the viewport rather than changing the width
- The submenus aren't accessible on mobile

**Comment by matthewaramis** [comment]
Main menu no longer has slight movement on hover and gap between link and submenu is gone. Mobile menu fixed.
