### ISSUE TITLE
Width for <p> is causing issues with mobile

### ISSUE THREAD

**Issue by benorgan** [redacademy/cnh-fall-2018#8]
Make sure you don't set a pixel width for paragraphs as it's introducing horizontal scroll on mobile
https://github.com/redacademy/cnh-fall-2018/blob/0d857bd33ac8cb82ffed69e35ed3ae4ba2d4bdaa/themes/cnh/sass/_service-page.scss#L29

**Comment by mikedd96** [comment]
width removed
